/** code generated by Kinyoshi */
package net.minecraft.src;

import java.io.*;
import java.util.*;
import net.minecraft.client.Minecraft;

public class mod_DesertCotton extends BaseMod
{
	public mod_DesertCotton()
	{

		readWriteProperties();

        BlockCottonPlant = (new BlockCottonPlant(BlockCottonPlantID)).setHardness(0.1F).setResistance(0.1F).setLightValue(0.0F).setStepSound(Block.soundClothFootstep).setUnlocalizedName("BlockCottonPlant");
        ModLoader.addName(BlockCottonPlant, "Cotton Plant");
        ModLoader.addRecipe(new ItemStack(Block.cloth, 1), new Object[] {"C", 'C', BlockCottonPlant});

    }

	public void readWriteProperties() {
		Properties properties = new Properties();
		try
		{
            File file = new File((new StringBuilder()).append(Minecraft.getMinecraftDir()).append("/mods/DesertCotton.config").toString());
            boolean flag = file.createNewFile();
            if(flag)
            {
                FileOutputStream fileoutputstream = new FileOutputStream(file);
                properties.setProperty("BlockCottonPlantID", Integer.toString(230));
                properties.store(fileoutputstream, "Change the ID's to fix ID incompatibilities.");
                fileoutputstream.close();
            }
            properties.load(new FileInputStream((new StringBuilder()).append(Minecraft.getMinecraftDir()).append("/mods/DesertCotton.config").toString()));
            BlockCottonPlantID = Integer.parseInt(properties.getProperty("BlockCottonPlantID"));
        }
        catch(IOException ioexception)
        {
            ioexception.printStackTrace();
            BlockCottonPlantID = 230;
        }
	}

    public void generateSurface(World var1, Random var2, int var3, int var4)
    {
            for (int var5 = 0; var5 <var2.nextInt(6) + 2; ++var5)
              {
               int var6 = var3 + var2.nextInt(16) + 2;
               int var7 = var2.nextInt(128);
               int var8 = var4 + var2.nextInt(16) + 2;
              (new WorldGenDesertCotton()).generate(var1, var2, var6, var7, var8);
              }	
    }

    public class WorldGenDesertCotton extends WorldGenerator
{
    public boolean generate(World var1, Random var2, int var3, int var4, int var5)
    {
        for (int var6 = 0; var6 < var2.nextInt(2); ++var6)
        {
            int var7 = var3 + var2.nextInt(16) - var2.nextInt(4);
            int var8 = var4;
            int var9 = var5 + var2.nextInt(16) - var2.nextInt(4);
            
            if (var1.isAirBlock(var7, var4, var9) && (var1.getBlockMaterial(var7 - 1, var4 - 1, var9) == Material.sand || var1.getBlockMaterial(var7 + 1, var4 - 1, var9) == Material.sand || var1.getBlockMaterial(var7, var4 - 1, var9 - 1) == Material.sand || var1.getBlockMaterial(var7, var4 - 1, var9 + 1) == Material.sand))
            {

                for (int var11 = 0; var11 < var2.nextInt(5) + 1; ++var11)
                {
                    if (BlockCottonPlant.canBlockStay(var1, var7, var8 + var11, var9))
                    {
                        var1.setBlock(var7, var8 + var11, var9, BlockCottonPlant.blockID);
                    }
                }
            }
        }

        return true;
    }
}
  
	public String getVersion() {
		return "MineCraft1.5.2__DesertCotton1.5.2r1";
	}

	public int addFuel(int par1, int par2)
    {
        if(par1 == BlockCottonPlant.blockID)
        {
            return 340;
        }
        return 0;
    }

    public static Block BlockCottonPlant;
    public static int BlockCottonPlantID;

	public void load()
	{
	  ModLoader.registerBlock(BlockCottonPlant);
	}
}
